require('jsdom-global')()
require('./support/tapedom')
require('./basic_test')
require('./children_test')
require('./dispatch_test')
require('./path_test')
require('./string_test')
require('./style_test')
require('./fix_props_test')
require('./deku/create_dom_renderer_test')
require('tape')('eslint', require('tape-eslint')())
